[versions]
#jetbrains
geocoderVersion = "3.9"
kotlin = "2.2.0"
kotlinxSerializationJson = "1.9.0"
#Detekt
detekt = "1.23.8"
detektCompose = "0.4.22"
#Eventbus
eventbus = "3.3.1"
#Fossify
commons = "4.3.0"
#Gradle
gradlePlugins-agp = "8.11.1"
#Other
indicatorFastScroll = "c7873f7168"
autofitTextView = "0.2.1"
libphonenumberVersion = "9.0.9"
#build
app-build-compileSDKVersion = "34"
app-build-targetSDK = "34"
app-build-minimumSDK = "26"
app-build-javaVersion = "VERSION_17"
app-build-kotlinJVMTarget = "17"
[libraries]
#Compose
compose-detekt = { module = "io.nlopez.compose.rules:detekt", version.ref = "detektCompose" }
#Fossify
fossify-commons = { module = "org.fossify:commons", version.ref = "commons" }
#EventBus
eventbus = { module = "org.greenrobot:eventbus", version.ref = "eventbus" }
#Kotlin
geocoder = { module = "com.googlecode.libphonenumber:geocoder", version.ref = "geocoderVersion" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
#Other
indicator-fast-scroll = { module = "org.fossify:IndicatorFastScroll", version.ref = "indicatorFastScroll" }
autofit-text-view = { module = "me.grantland:autofittextview", version.ref = "autofitTextView" }
libphonenumber = { module = "com.googlecode.libphonenumber:libphonenumber", version.ref = "libphonenumberVersion" }
[plugins]
android = { id = "com.android.application", version.ref = "gradlePlugins-agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
